### ISSUE TITLE
TypeError: Cannot read property 'Symbol(duplicates)' of undefined

### ISSUE THREAD

**Issue by goto-bus-stop** [goto-bus-stop/common-shakeify#10]
`getDuplicates` fails with this when i use `browserify --no-bundle-external`.

```
  return row[kDuplicates] || []
             ^

TypeError: Cannot read property 'Symbol(duplicates)' of undefined
    at getDuplicates (/home/arch/Code/goto-bus-stop/common-shakeify/index.js:214:14)
    at analyzer.modules.forEach (/home/arch/Code/goto-bus-stop/common-shakeify/index.js:115:21)
```

**Comment by moszeed** [comment]
hi, i`m still getting this error on my test code,
with Version 0.4.2 and the "browserify -p [ common-shakeify -v ]" command ...
```
/commshaketest/node_modules/common-shakeify/index.js:216
  return row[kDuplicates] || []
            ^

TypeError: Cannot read property 'Symbol(duplicates)' of undefined
    at getDuplicates (/commshaketest/node_modules/common-shakeify/index.js:216:13)
    at analyzer.modules.forEach (/commshaketest/node_modules/common-shakeify/index.js:117:21)
    at Map.forEach (native)
    at DestroyableTransform.onend [as _flush] (/commshaketest/node_modules/common-shakeify/index.js:114:22)
    at DestroyableTransform.<anonymous> (/commshaketest/node_modules/readable-stream/lib/_stream_transform.js:138:49)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at prefinish (/commshaketest/node_modules/readable-stream/lib/_stream_writable.js:596:14)
    at finishMaybe (/commshaketest/node_modules/readable-stream/lib/_stream_writable.js:604:5)
```

**Comment by goto-bus-stop** [comment]
hmm i see. could you share a reproduction?

**Comment by moszeed** [comment]
i will try to reduce the used file  (was a very big from our company repo, with many requires) to get a smaller example ...

**Comment by goto-bus-stop** [comment]
gotcha, that would be great! thanks!

**Comment by moszeed** [comment]
🙈 
found it, i think its my fault,
the error occurs on following command:
```
browserify ./client/scripts/pages/test.js ${EXTERNALS} ${PLUGINS} \
    -r ./client/scripts/classes/Test.class.js:Test \
    -r ./client/scripts/pages/page-price.js:page-price \
    -o ./dist/js/pages/page-price.js ${TRANSFORM}
```

i`m using the "-r" parameter 2 times ...

**Comment by goto-bus-stop** [comment]
Ahh I see, so common-shakeify breaks when using `-r`.  there's nothing wrong with how you're using it. i'll try to fix in #11

**Comment by goto-bus-stop** [comment]
📦 `0.4.4` should fix this finally :)

**Comment by AVVS** [comment]
Same error on 0.4.5, but my config is quite weird, maybe I should do something better or doing something wrong, but I cant see what it could possibly be

```
[17:59:56] TypeError: Cannot read property 'Symbol(duplicates)' of undefined
    at getDuplicates (/Users/vitaly/projects/cappasity-player/node_modules/common-shakeify/index.js:222:13)
    at analyzer.modules.forEach (/Users/vitaly/projects/cappasity-player/node_modules/common-shakeify/index.js:121:21)
    at Map.forEach (<anonymous>)
    at DestroyableTransform.onend [as _flush] (/Users/vitaly/projects/cappasity-player/node_modules/common-shakeify/index.js:118:22)
    at DestroyableTransform.<anonymous> (/Users/vitaly/projects/cappasity-player/node_modules/readable-stream/lib/_stream_transform.js:138:49)
    at Object.onceWrapper (events.js:255:19)
    at DestroyableTransform.emit (events.js:160:13)
    at prefinish (/Users/vitaly/projects/cappasity-player/node_modules/readable-stream/lib/_stream_writable.js:596:14)
    at finishMaybe (/Users/vitaly/projects/cappasity-player/node_modules/readable-stream/lib/_stream_writable.js:604:5)
    at endWritable (/Users/vitaly/projects/cappasity-player/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at DestroyableTransform.Writable.end (/Users/vitaly/projects/cappasity-player/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at Labeled.<anonymous> (/Users/vitaly/projects/cappasity-player/node_modules/stream-splicer/index.js:43:26)
    at Object.onceWrapper (events.js:255:19)
    at Labeled.emit (events.js:165:20)
    at finishMaybe (/Users/vitaly/projects/cappasity-player/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at endWritable (/Users/vitaly/projects/cappasity-player/node_modules/readable-stream/lib/_stream_writable.js:615:3)
```

```
// external
const external = config.external = [
  'three',
  'three/examples/js/Detector',
  'buffer',
  // 'babel-runtime',
  'pino',
  'is-buffer',
  'axios',
  'eventemitter3',
  'hammerjs',
  'bluebird',
  'progressbar.js',
  'jws',
  'raf',
  'qs/lib/parse',
  'raven-js',
  'raven-js/plugins/vue',
  'platform',
  'webfontloader',
  'vue',
  'vuex',
  'lodash/get',
  'lodash/find',
  'lodash/assign',
  'lodash/forEach',
  'lodash/pick',
  'lodash/mapValues',
  'spark-md5',
];

const options = {
  paths: ['node_modules', 'src'],
  debug: true,
  fullPaths: false,
  cache: {},
  packageCache: {},
  builtins: {
    ...omit(builtins, 'buffer'),
    vm: require.resolve('browserify/lib/_empty'),
  },
  noParse: ['three', 'bluebird'],
  externalRequireName: '_der_',
  require: external.slice(3), /* excludes three.js, buffer, babel-runtime */
  external: external.slice(2, 3), /* buffer, babel-runtime */
  plugin: [],
  entries: ['./src/raven.js'],
};

const Vendor = browserify(options);

bundler.transform('envify', {
...
}

bundler.transform('babelify', { global: true });

// uses tinyify under the hood, just remapped uglify options and made some opts
// configurable
bundler.plugin('./vendor/tinyify', {
      uglify: config.uglify,
      shake: true,
      flat: true,
});
```
