### ISSUE TITLE
Some kind of error sometimes

### ISSUE THREAD

**Issue by laduke** [goto-bus-stop/common-shakeify#9]
So, if I have `pull-ws` in my `choo` app and use `bankai` as the dev server, bankai will crash when it first starts up; Then if I save a file, it recompiles and it works. 

Chatted with @yoshuawuyts and we narrowed it down to common-shakeify by commenting out transforms in `bankai` (https://github.com/choojs/bankai/blob/master/lib/graph-script.js) until it worked. 

Here's is the stack trace. 
```
scripts:browserify.bundle Assigning to rvalue (3:45)
SyntaxError: Assigning to rvalue (3:45)
    at Parser.pp$4.raise (/Users/travis/source/commonshake/node_modules/acorn/dist/acorn.js:2610:13)
    at Parser.pp$2.toAssignable (/Users/travis/source/commonshake/node_modules/acorn/dist/acorn.js:1529:12)
    at Parser.pp$3.parseMaybeAssign (/Users/travis/source/commonshake/node_modules/acorn/dist/acorn.js:1839:47)
    at Parser.pp$3.parseExpression (/Users/travis/source/commonshake/node_modules/acorn/dist/acorn.js:1803:19)
    at Parser.pp$1.parseStatement (/Users/travis/source/commonshake/node_modules/acorn/dist/acorn.js:797:45)
    at Parser.pp$1.parseTopLevel (/Users/travis/source/commonshake/node_modules/acorn/dist/acorn.js:690:23)
    at Parser.parse (/Users/travis/source/commonshake/node_modules/acorn/dist/acorn.js:543:15)
    at parse (/Users/travis/source/commonshake/node_modules/acorn/dist/acorn.js:3669:37)
    at module.exports (/Users/travis/source/commonshake/node_modules/falafel/index.js:22:15)
    at /Users/travis/source/commonshake/node_modules/static-module/index.js:30:13
```

I made a repro repo 
https://gist.github.com/laduke/7441c3564d74905f6d409924bccbf68f

**Comment by goto-bus-stop** [comment]
Thanks! fixed in 0.4.1 🎉 

It was replacing

```js
exports.decode = exports.parse = require('./decode');
exports.encode = exports.stringify = require('./encode');
```

with


```js
/* common-shake removed: exports.decode = */ void exports.parse = require('./decode');
/* common-shake removed: exports.encode = */ void exports.stringify = require('./encode');
```
